version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: veiculos-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: veiculosdb
      # Timezone
      TZ: America/Sao_Paulo
    ports:
      - "54321:5432"
    volumes:
      # Volume para persistência dos dados
      - postgres-data:/var/lib/postgresql/data
      # Script de inicialização com os 30 veículos
      - ./init.sql:/docker-entrypoint-initdb.d/001-init.sql
    networks:
      - veiculos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d veiculosdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
    driver: local

networks:
  veiculos-network:
    driver: bridge